# Mengatur level log ke INFO dan output ke console (stdout)
log4j.rootLogger=INFO, stdout

# Konfigurasi untuk mencetak ke Terminal
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.Target=System.out
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
# Format pesan log (Tanggal Waktu | Level | Pesan)
log4j.appender.stdout.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} [%-5p] %c{1} - %m%n